-- CHECK IF WE ALREADY HAVE DATA

DO $$
BEGIN
    IF (SELECT COUNT(*) FROM plans WHERE id = 'solo-plan-001') > 0 THEN
        RAISE EXCEPTION 'Plans already exist. Cannot seed data.';
    END IF;
END $$;

INSERT INTO plans (
    id,
    dodo_plan_id,
    name,
    description,
    status,
    price,
    currency,
    price_per_seat,
    billing_cycle,
    trial_period_days,
    trial_enabled,
    display_order,
    is_popular,
    is_enterprise,
    metadata,
    created_at,
    updated_at
) VALUES 
    (
        'solo-plan-001',
        'dodo-solo-001',
        'Solo',
        'For individuals getting started with email automation',
        'active',
        0.00,
        'USD',
        0.00,
        'MONTHLY',
        0,
        false,
        1,
        false,
        false,
        '{}',
        NOW(),
        NOW()
    ),
    (
        'starter-monthly-001',
        'pdt_0Ncs1hupmJmnhnYEVjIHG',
        'Starter (Monthly)',
        'For small teams and indie hackers scaling up',
        'active',
        6.99,
        'USD',
        6.99,
        'MONTHLY',
        0,
        false,
        2,
        true,
        false,
        '{}',
        NOW(),
        NOW()
    ),
    (
        'starter-yearly-001',
        'pdt_0Ncs1iI8DNTOCxTqKfID3',
        'Starter (Yearly)',
        'For small teams and indie hackers scaling up with yearly billing',
        'active',
        66.00,
        'USD',
        66.00,
        'YEARLY',
        0,
        false,
        3,
        false,
        false,
        '{}',
        NOW(),
        NOW()
    ),
    (
        'pro-monthly-001',
        'pdt_0Ncs1gXvdM1yC4DO06gKk',
        'Pro (Monthly)',
        'For teams who want full automation',
        'active',
        16.99,
        'USD',
        16.99,
        'MONTHLY',
        0,
        false,
        4,
        false,
        false,
        '{}',
        NOW(),
        NOW()
    ),
    (
        'pro-yearly-001',
        'pdt_0Ncs1hP7IALYcO0pDeLEF',
        'Pro (Yearly)',
        'For teams who want full automation with yearly billing',
        'active',
        166.00,
        'USD',
        166.00,
        'YEARLY',
        0,
        false,
        5,
        false,
        false,
        '{}',
        NOW(),
        NOW()
    ),
    (
        'enterprise-plan-001',
        'dodo-enterprise-001',
        'Enterprise',
        'For growing teams that need control',
        'active',
        -1.00,
        'USD',
        -1.00,
        'YEARLY',
        0,
        false,
        6,
        false,
        true,
        '{}',
        NOW(),
        NOW()
    );

-- Seed data for plan_features table

INSERT INTO plan_features (
    id,
    plan_id,
    quota,
    feature,
    created_at,
    updated_at,
    trail
) VALUES
    -- Solo Plan Features
    (
        'solo-emails-001',
        'solo-plan-001',
        500,
        'emails_per_month',
        NOW(),
        NOW(),
        false
    ),
    (
        'solo-smtp-001',
        'solo-plan-001',
        1,
        'smtp_providers',
        NOW(),
        NOW(),
        false
    ),
    (
        'solo-templates-001',
        'solo-plan-001',
        1,
        'basic_templates',
        NOW(),
        NOW(),
        false
    ),
    (
        'solo-support-001',
        'solo-plan-001',
        1,
        'community_support',
        NOW(),
        NOW(),
        false
    ),
    (
        'solo-selfhost-001',
        'solo-plan-001',
        1,
        'self_hosting',
        NOW(),
        NOW(),
        false
    ),
    -- Starter Monthly Plan Features
    (
        'starter-monthly-emails-001',
        'starter-monthly-001',
        5000,
        'emails_per_month',
        NOW(),
        NOW(),
        false
    ),
    (
        'starter-monthly-smtp-001',
        'starter-monthly-001',
        5,
        'smtp_providers',
        NOW(),
        NOW(),
        false
    ),
    (
        'starter-monthly-templates-001',
        'starter-monthly-001',
        1,
        'custom_templates',
        NOW(),
        NOW(),
        false
    ),
    (
        'starter-monthly-support-001',
        'starter-monthly-001',
        1,
        'community_support',
        NOW(),
        NOW(),
        false
    ),
    (
        'starter-monthly-selfhost-001',
        'starter-monthly-001',
        1,
        'self_hosting',
        NOW(),
        NOW(),
        false
    ),
    (
        'starter-monthly-analytics-001',
        'starter-monthly-001',
        1,
        'basic_analytics',
        NOW(),
        NOW(),
        false
    ),
    (
        'starter-monthly-integrations-001',
        'starter-monthly-001',
        1,
        'limited_integrations',
        NOW(),
        NOW(),
        false
    ),
    -- Starter Yearly Plan Features
    (
        'starter-yearly-emails-001',
        'starter-yearly-001',
        5000,
        'emails_per_month',
        NOW(),
        NOW(),
        false
    ),
    (
        'starter-yearly-smtp-001',
        'starter-yearly-001',
        5,
        'smtp_providers',
        NOW(),
        NOW(),
        false
    ),
    (
        'starter-yearly-templates-001',
        'starter-yearly-001',
        1,
        'custom_templates',
        NOW(),
        NOW(),
        false
    ),
    (
        'starter-yearly-support-001',
        'starter-yearly-001',
        1,
        'community_support',
        NOW(),
        NOW(),
        false
    ),
    (
        'starter-yearly-selfhost-001',
        'starter-yearly-001',
        1,
        'self_hosting',
        NOW(),
        NOW(),
        false
    ),
    (
        'starter-yearly-analytics-001',
        'starter-yearly-001',
        1,
        'basic_analytics',
        NOW(),
        NOW(),
        false
    ),
    (
        'starter-yearly-integrations-001',
        'starter-yearly-001',
        1,
        'limited_integrations',
        NOW(),
        NOW(),
        false
    ),
    -- Pro Monthly Plan Features
    (
        'pro-monthly-emails-001',
        'pro-monthly-001',
        -1, -- -1 means unlimited
        'emails_per_month',
        NOW(),
        NOW(),
        false
    ),
    (
        'pro-monthly-smtp-001',
        'pro-monthly-001',
        -1,
        'smtp_providers',
        NOW(),
        NOW(),
        false
    ),
    (
        'pro-monthly-templates-001',
        'pro-monthly-001',
        1,
        'advanced_templates',
        NOW(),
        NOW(),
        false
    ),
    (
        'pro-monthly-analytics-001',
        'pro-monthly-001',
        1,
        'advanced_analytics',
        NOW(),
        NOW(),
        false
    ),
    (
        'pro-monthly-support-001',
        'pro-monthly-001',
        1,
        'priority_support',
        NOW(),
        NOW(),
        false
    ),
    (
        'pro-monthly-integrations-001',
        'pro-monthly-001',
        1,
        'all_integrations',
        NOW(),
        NOW(),
        false
    ),
    -- Pro Yearly Plan Features
    (
        'pro-yearly-emails-001',
        'pro-yearly-001',
        -1, -- -1 means unlimited
        'emails_per_month',
        NOW(),
        NOW(),
        false
    ),
    (
        'pro-yearly-smtp-001',
        'pro-yearly-001',
        -1,
        'smtp_providers',
        NOW(),
        NOW(),
        false
    ),
    (
        'pro-yearly-templates-001',
        'pro-yearly-001',
        1,
        'advanced_templates',
        NOW(),
        NOW(),
        false
    ),
    (
        'pro-yearly-analytics-001',
        'pro-yearly-001',
        1,
        'advanced_analytics',
        NOW(),
        NOW(),
        false
    ),
    (
        'pro-yearly-support-001',
        'pro-yearly-001',
        1,
        'priority_support',
        NOW(),
        NOW(),
        false
    ),
    (
        'pro-yearly-integrations-001',
        'pro-yearly-001',
        1,
        'all_integrations',
        NOW(),
        NOW(),
        false
    ),
    -- Enterprise Plan Features
    (
        'enterprise-emails-001',
        'enterprise-plan-001',
        -1,
        'emails_per_month',
        NOW(),
        NOW(),
        false
    ),
    (
        'enterprise-smtp-001',
        'enterprise-plan-001',
        -1,
        'smtp_providers',
        NOW(),
        NOW(),
        false
    ),
    (
        'enterprise-templates-001',
        'enterprise-plan-001',
        1,
        'advanced_templates',
        NOW(),
        NOW(),
        false
    ),
    (
        'enterprise-analytics-001',
        'enterprise-plan-001',
        1,
        'advanced_analytics',
        NOW(),
        NOW(),
        false
    ),
    (
        'enterprise-integrations-001',
        'enterprise-plan-001',
        1,
        'all_integrations',
        NOW(),
        NOW(),
        false
    ),
    (
        'enterprise-workspaces-001',
        'enterprise-plan-001',
        1,
        'team_workspaces',
        NOW(),
        NOW(),
        false
    ),
    (
        'enterprise-account-manager-001',
        'enterprise-plan-001',
        1,
        'dedicated_account_manager',
        NOW(),
        NOW(),
        false
    ),
    (
        'enterprise-whitelabel-001',
        'enterprise-plan-001',
        1,
        'white_label',
        NOW(),
        NOW(),
        false
    ),
    (
        'enterprise-sla-001',
        'enterprise-plan-001',
        1,
        'sla_guarantee',
        NOW(),
        NOW(),
        false
    ),
    (
        'enterprise-onpremises-001',
        'enterprise-plan-001',
        1,
        'on_premises_support',
        NOW(),
        NOW(),
        false
    );